version: '3'

services:
  wsp-autoattend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Almaty
    restart: unless-stopped
    volumes:
      - ./chrome_sessions:/app/chrome_sessions